const env = process.env.NODE_ENV || 'development';
const serverIP = 'localhost';
const serverPort = 5000;
module.exports = {
  CUSTOMER: 'customer',
  CREATOR: 'creator',
  CONTEST_STATUS_ACTIVE: 'active',
  CONTEST_STATUS_FINISHED: 'finished',
  CONTEST_STATUS_PENDING: 'pending',
  NAME_CONTEST: 'name',
  LOGO_CONTEST: 'logo',
  TAGLINE_CONTEST: 'tagline',
  OFFER_STATUS_REJECTED: 'rejected',
  OFFER_STATUS_WON: 'won',
  OFFER_STATUS_PENDING: 'pending',
  STATIC_IMAGES_PATH: '/staticImages/',
  ANONYM_IMAGE_PATH: '/staticImages/anonym.png',
  HOW_IT_WORKS_HEADER_BACKGROUND: '/howItWorks/header/backgroundTopHeader.png',
  HOW_IT_WORKS_HEADER_LOGO_ATOM: '/howItWorks/header/logoAtom.png',
  HOW_IT_WORKS_HEADER_ICON_PREMIUM: '/howItWorks/header/icon1.svg',
  HOW_IT_WORKS_HEADER_ICON_ULTRA: '/howItWorks/header/icon2.svg',
  HOW_IT_WORKS_HEADER_ICON_SAPPHIRE: '/howItWorks/header/icon3.svg',
  HOW_IT_WORKS_HEADER_ICON_WORK_PROCESS: '/howItWorks/header/icon4.png',
  HOW_IT_WORKS_HEADER_ICON_DUNDRUFF: '/howItWorks/header/icon5.svg',
  HOW_IT_WORKS_HEADER_ICON_WORK_PROCESS_BACKGROUND:
    '/howItWorks/header/icon6.svg',
  HOW_IT_WORKS_HEADER_ICON_GENERATOR: '/howItWorks/header/icon7.svg',
  HOW_IT_WORKS_HEADER_ICON_TOOL: '/howItWorks/header/icon8.svg',
  HOW_IT_WORKS_HEADER_ICON_LOOKUP: '/howItWorks/header/icon9.svg',
  HOW_IT_WORKS_HEADER_ICON_CONTEST: '/howItWorks/header/icon10.svg',
  HOW_IT_WORKS_HEADER_ICON_AGENCY: '/howItWorks/header/icon11.svg',
  HOW_IT_WORKS_HEADER_ICON_LOGO_GENERATOR: '/howItWorks/header/icon12.svg',
  HOW_IT_WORKS_HEADER_ICON_RESEARCH: '/howItWorks/header/icon13.svg',
  HOW_IT_WORKS_HEADER_ICON_TRADEMARK: '/howItWorks/header/icon14.svg',
  HOW_IT_WORKS_HEADER_ICON_MONITORING: '/howItWorks/header/icon15.svg',
  HOW_IT_WORKS_HEADER_ICON_NETWORK_API: '/howItWorks/header/icon16.svg',
  HOW_IT_WORKS_HEADER_ICON_MCP_SERVER: '/howItWorks/header/icon17.svg', 
  HOW_IT_WORKS_HEADER_ICON_LABEL: '/howItWorks/header/icon18.svg', 
  HOW_IT_WORKS_HEADER_ICON_ATOM_CONNECT: '/howItWorks/header/icon19.svg', 
  HOW_IT_WORKS_HEADER_ICON_SEARCH: '/howItWorks/header/icon20.svg', 
  HOW_IT_WORKS_HEADER_ICON_SEARCH_WHITE: '/howItWorks/header/icon21.svg', 
  HOW_IT_WORKS_HEADER_ICON_USER: '/howItWorks/header/icon22.svg', 
  HOW_IT_WORKS_HEADER_ICON_USER_FORM: '/howItWorks/header/icon23.svg',
  HOW_IT_WORKS_HEADER_ICON_PHONE: '/howItWorks/header/icon24.svg',
  HOW_IT_WORKS_HEADER_ICON_CHAT: '/howItWorks/header/icon25.svg',  
  HOW_IT_WORKS_HEADER_ICON_EMAIL: '/howItWorks/header/icon26.svg',  
  HOW_IT_WORKS_HEADER_ICON_HELP_DESK: '/howItWorks/header/icon27.svg',    
  HOW_IT_WORKS_HEADER_ICON_ARROW: '/howItWorks/header/iconArrow.svg',
  HOW_IT_WORKS_HEADER_ICON_HEART: '/howItWorks/header/icon28.svg', 
  HOW_IT_WORKS_HEADER_ICON_SEARCH_ARROW: '/howItWorks/header/icon29.svg',
  HOW_IT_WORKS_HEADER_ICON_ARROW_DOWN: '/howItWorks/header/icon30.svg',
  HOW_IT_WORKS_SECTION_ICON_ARROW:'/howItWorks/mainSection/icon1.svg',
  HOW_IT_WORKS_SECTION_ICON_FLASH:'/howItWorks/mainSection/icon2.svg',
  HOW_IT_WORKS_SECTION_ICON_MONITOR:'/howItWorks/mainSection/icon3.svg',
  HOW_IT_WORKS_SECTION_ICON_LIGHT:'/howItWorks/mainSection/icon4.svg',
  HOW_IT_WORKS_SECTION_ICON_CUP:'/howItWorks/mainSection/icon5.svg', 
  HOW_IT_WORKS_SECTION_ICON_STEP_ARROW:'/howItWorks/mainSection/icon6.svg',    
  HOW_IT_WORKS_SECTION_ICON_PLUS:'/howItWorks/mainSection/icon7.svg', 
  HOW_IT_WORKS_SECTION_ICON_X:'/howItWorks/mainSection/icon8.svg',   
  BASE_URL: `http://${serverIP}:${serverPort}/`,
  ACCESS_TOKEN: 'accessToken',
  publicURL:
    env === 'production'
      ? `http://${serverIP}:80/images/`
      : `http://${serverIP}:${serverPort}/public/images/`,
  NORMAL_PREVIEW_CHAT_MODE: 'NORMAL_PREVIEW_CHAT_MODE',
  FAVORITE_PREVIEW_CHAT_MODE: 'FAVORITE_PREVIEW_CHAT_MODE',
  BLOCKED_PREVIEW_CHAT_MODE: 'BLOCKED_PREVIEW_CHAT_MODE',
  CATALOG_PREVIEW_CHAT_MODE: 'CATALOG_PREVIEW_CHAT_MODE',
  CHANGE_BLOCK_STATUS: 'CHANGE_BLOCK_STATUS',
  ADD_CHAT_TO_OLD_CATALOG: 'ADD_CHAT_TO_OLD_CATALOG',
  CREATE_NEW_CATALOG_AND_ADD_CHAT: 'CREATE_NEW_CATALOG_AND_ADD_CHAT',
  USER_INFO_MODE: 'USER_INFO_MODE',
  CASHOUT_MODE: 'CASHOUT_MODE',
  AUTH_MODE: {
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
  },
  HEADER_ANIMATION_TEXT: [
    'a Company',
    'a Brand',
    'a Website',
    'a Service',
    'a Book',
    'a Business',
    'an App',
    'a Product',
    'a Startup',
  ],
  FooterItems: [
    {
      title: 'SQUADHELP',
      items: ['About', 'Contact', 'How It Works?', 'Testimonials', 'Our Work'],
    },
    {
      title: 'RESOURCES',
      items: [
        'How It Works',
        'Become a Creative',
        'Business Name Generator',
        'Discussion Forum',
        'Blog',
        'Download eBook',
        'Pricing',
        'Help & FAQs',
      ],
    },
    {
      title: 'OUR SERVICES',
      items: [
        'Naming',
        'Logo Design',
        'Taglines',
        'Premium Names For Sale',
        'Creative Owned Names For Sale',
        'Audience Testing',
        'Trademark Research & Filling',
        'Managed Agency Service',
      ],
    },
    {
      title: 'LEGAL',
      items: ['Terms of Service', 'Privacy Policy', 'Cookie Policy'],
    },
  ],
};
