CREATE TABLE IF NOT EXISTS "Catalogs"(
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "Users"(id) ON DELETE RESTRICT,
    catalog_name VARCHAR(64) CHECK(catalog_name != '') NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Conversations"(
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Catalogs_Conversations"(
    catalog_id INTEGER NOT NULL REFERENCES "Catalogs"(id) ON DELETE CASCADE,
    conversation_id INTEGER NOT NULL REFERENCES "Conversations"(id) ON DELETE CASCADE,
    PRIMARY KEY(catalog_id, conversation_id)
);

 CREATE TABLE IF NOT EXISTS "Messages"(
    id SERIAL PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES "Conversations"(id) ON DELETE CASCADE,
    sender INTEGER NOT NULL REFERENCES "Users"(id) ON DELETE RESTRICT,
    body TEXT CHECK(body != '') NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Conversations_Users"(
    conversation_id INTEGER NOT NULL REFERENCES "Conversations"(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES "Users"(id) ON DELETE RESTRICT,
    black_list BOOLEAN NOT NULL DEFAULT FALSE,
    favorite_list BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(conversation_id, user_id)
);